# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 06:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0002_auto_20160113_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='www.baidu.com', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
