# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0007_remove_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='creator',
            field=models.CharField(default='rango', max_length=100),
        ),
    ]
