# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_category_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slugf',
            field=models.SlugField(default='111'),
        ),
    ]
