# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-13 10:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0009_category_slugf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slugf',
            new_name='slug',
        ),
    ]
